---
title: "FinalProject"
author: "Joshua Sum"
date: "2/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Potential Business Questions
- What is the ideal Shark Tank pitch that gives a competitor the best shot of getting funded at the highest valuation?
- Which target should you try to tailor your pitch to, depending on what your company does?

# Shark Tank Data
We obtained our data from a Kaggle project https://www.kaggle.com/zabonpan/shark-tank-pitches-deals-season-111
```{r}
data <- read.csv("SharkTankData.csv")
data$Episode <- as.factor(data$Episode)
data$Deal <- as.factor(data$Deal)
data$Category <- as.factor(data$Category)
data$Entrepreneur.Gender <- as.factor(data$Entrepreneur.Gender)
data$ASK_Equity <- as.numeric(substr(data$ASK_Equity,1,nchar(data$ASK_Equity)-1))/100
data$ASK_Amount <- as.numeric(gsub(",", "", data$ASK_Amount))
data$ASK_Valuation <- as.numeric(gsub(",", "", data$ASK_Valuation))
data$DEAL_Equity <- as.numeric(substr(data$DEAL_Equity,1,nchar(data$DEAL_Equity)-1))/100
data$DEAL_Amount <- as.numeric(gsub(",", "", data$DEAL_Amount))
data$DEAL_Valuation <- as.numeric(gsub(",", "", data$DEAL_Valuation))
data$Royalty <- as.factor(data$Royalty)
data$Loan <- as.factor(as.numeric(data$Loan))
data$Barbara.Corcoran <- as.factor(data$Barbara.Corcoran)
data$Mark.Cuban <- as.factor(data$Mark.Cuban)
data$Lori.Greiner <- as.factor(data$Lori.Greiner)
data$Robert.Herjavec <- as.factor(data$Robert.Herjavec)
data$Daymond.John <- as.factor(data$Daymond.John)
data$Kevin.O.Leary <- as.factor(data$Kevin.O.Leary)
data$Guest <- as.factor(data$Guest)
data$State <- NULL
data$Investment.shark <- as.numeric(gsub(",", "", data$Investment.shark))

# Taking subset of season 5 onwards
data <- subset(data, Season >= 5)
data$Season <- as.factor(data$Season)

summary(data)
```


# 

```{r}

```

